#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Change these two as needed
#define DURATION 1600
#define TIMESTEP 1

// DON'T CHANGE THESE
// Masks and size of int for writing to file later.
// Its because the library for writing to files on flash
// is hacky and limited.
#define LOWER_MASK 0x00FF
#define UPPER_MASK 0xFF00
#define TYPE_SIZE 2
// END DON'T CHANGE

#include <../jpearman-lib/FlashLib.h>

int datapoints = DURATION/TIMESTEP;
static int numData[DURATION / TIMESTEP]; //should equal datapoints, but must be written as constant
static unsigned char numDataStorage[DURATION / TIMESTEP * TYPE_SIZE];

task main()
{
	// DON'T CHANGE
	unsigned char * data;
	int datalength;
	char lastname[16];
	int result;
	// END DON'T CHANGE

	/////////////////////////////////////////////////////////////
	// This is where you should put your program
	// Store the data you wish to save in numData
	// Define DURATION and TIMESTEP at the top (must be integers)

	// initialize to 0
	SensorValue(encoder) = 0;
	motor[motor1] = 0;

	// 100ms 0 data
	for(int i = 0; i<100; i++)
	{
		wait1Msec(TIMESTEP);
		numData[i] = SensorValue(encoder);
  }

  // accelerate to full speed in 500ms
  for(int i=100; i<600; i++)
	{
		motor[motor1] = -127;
		wait1Msec(TIMESTEP);
		numData[i] = SensorValue(encoder);
	}

	// decelerate to zero in 1000ms
	for(int i=600; i<1600; i++)
	{
		motor[motor1] = 0;
		wait1Msec(TIMESTEP);
		numData[i] = SensorValue(encoder);
	}

	// check to make sure 0 was reached
	motor[motor1] = 100;
	wait1Msec(1000);
	motor[motor1] = 0;

	//
	//
	///////////////////////////////////////////////////////////////

	/***************************
	 *                         *
	 *  DO NOT EDIT PAST HERE  *
	 * WRITING numData TO FILE *
	 *                         *
	 ***************************/

	// Prep data for storage
	for(int i=0; i<datapoints; i++)
	{
		numDataStorage[TYPE_SIZE*i] = (unsigned char) (numData[i] & LOWER_MASK);
		numDataStorage[TYPE_SIZE*i+1] = (unsigned char) ((numData[i] & UPPER_MASK) >> 8);
  }

  // Create & Write to File
	result = RCFS_AddFile(numDataStorage, datapoints * TYPE_SIZE);

	// Dump directory
	RCFS_ReadVTOC();

	// Get the name of the last file written
	RCFS_GetLastFilename(lastname, 16);

	// Get a pointer to the data in that last file
	// Pass the address of the data pointer (called a handle)
	result = RCFS_GetFile(lastname, &data, &datalength);

	wait1Msec(500);
}
