#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <jpearman-lib/FlashLib.h>

task main()
{
    int   i;
    unsigned char *data;
    int           datalength;
    char    lastname[16];

			// Get the name and data of the last file written
			RCFS_GetLastFilename(lastname, 16);
			RCFS_GetFile(lastname, &data, &datalength);

			// rerun sensor/joystick motor values
			for(i=0;i<datalength;i++)
			{
				motor[motor1] = data[i];
				wait1Msec(10);
			}
}
