#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           motor1,        tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <jpearman-lib/FlashLib.h>

static char tmpData[1000];

task main()
{
    int   i;
    unsigned char *data;
    int           datalength;
    char    lastname[16];

    // create some test data with motor and sensor
    // you'll want to modify so motor follows joystick rather than encoder
    for(i=0;i<1000;i++)
    {
    		motor[motor1] = SensorValue(encoder);
        tmpData[i] = motor[motor1];
        wait1Msec(10);
      }

      motor[motor1] = 0;
      wait1Msec(2000);

      // write file, dump directory
			RCFS_AddFile(tmpData, 1000);
      RCFS_ReadVTOC();

			// Recall data stored in data[]
			RCFS_GetLastFilename(lastname, 16);
			RCFS_GetFile(lastname, &data, &datalength);

			// rerun sensor/joystick motor values
			for(i=0;i<datalength;i++)
			{
				motor[motor1] = data[i];
				wait1Msec(10);
			}
}
